Final
PavelShipilo/firstTask pull request #11
Opened 2020-02-06 21:11 UTC by PavelShipilo

2020-02-07 08:00 UTC, TanyaAndreeva requested changes

2020-02-07 08:00 UTC, TanyaAndreeva commented on DataTypes.js
> +console.log(typeof String(12));//'12'
можно использовать x.toString()

2020-02-07 08:00 UTC, TanyaAndreeva commented on DataTypes.js
> +alert(Boolean(' '));//true
необходимо оставлять пустую строку в конце файла

2020-02-07 08:00 UTC, TanyaAndreeva commented on Operators.js
> +	b = 1;
выровнять табуляцию

2020-02-07 08:00 UTC, TanyaAndreeva commented on Operators.js
> +null === +"\n0\n" //false
необходимо оставлять пустую строку в конце файла

2020-02-07 08:00 UTC, TanyaAndreeva commented on arrays.js
> +}
сделай Format Document , строки все на разном уровне )

2020-02-07 08:00 UTC, TanyaAndreeva commented on arrays.js
> +{
когда открываем скобку в функции она находится на той строке где и название , не надо ее переносить

2020-02-07 08:00 UTC, TanyaAndreeva commented on arrays.js
> +	{
то же самое со скобочкой

2020-02-07 08:00 UTC, TanyaAndreeva commented on arrays.js
> +	{
этот цикл будет бесконечный

2020-02-07 08:00 UTC, TanyaAndreeva commented on arrays.js
> +		if (value === "" || value === null || !isFinite(value)) break;
это условие должно быть в while , в этом и было задание, что бы выйти из цикла без break, а тогда когда условие совпадает в while

2020-02-07 08:00 UTC, TanyaAndreeva commented on arrays.js
> +
лишний пробел между строк

2020-02-07 08:00 UTC, TanyaAndreeva commented on arrays.js
> +	{
скобочку не надо переносить на новую строку

2020-02-07 08:00 UTC, TanyaAndreeva commented on arrays.js
> +{
скобочку не надо переносить

2020-02-07 08:00 UTC, TanyaAndreeva commented on arrays.js
> +	{
скобочку не переносить

2020-02-07 08:00 UTC, TanyaAndreeva commented on arrays.js
> +}
надо оставлять пустую строку

2020-02-11 10:07 UTC, PavelShipilo commented
...

2020-03-01 19:02 UTC, merged